import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import React from 'react'
import { cookies } from 'next/headers';
import GoToTopButton from '../components/GoToTopButton'

const hurmeFont = localFont({
  src: './fonts/HurmeGeometricSans1-Regular.woff2',
  display: 'swap',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ecommerce App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  const cartId = (await cookies()).get('cartId')?.value;

  return (
    <html lang="en">
      <body className={hurmeFont.className}>
        <Navbar />
        {children}
        <GoToTopButton />
        <Footer />
      </body>
    </html>
  )
}
